# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Parse Benchmark
title: Parse Benchmark
email: community@parseplatform.org
description: Parse Server Continuous Benchmark Page
url: "http://parseplatform.org/benchmark"
repository: parse-community/benchmark
twitter_username:  parseplatform
github_username:   parseplatform
stackoverflow_tag: parse-platform
serverfault_tag:   parse
support_url: https://community.parseplatform.org

# Build settings
markdown: kramdown
exclude: [ Gemfile, Gemfile.lock, README.md, config.codekit, webpack.config.js, node_modules, npm-debug.log, package.json ]
sass:
  sass_dir: css

# Gems
plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
